#include <vector>
#include <map>
#include <string>
#include <cstring>
#include <string.h>
using namespace std;

typedef vector<int> INTVECT;
typedef vector<string> STRVECT;
typedef vector<double> DBLVECT;

typedef map<string,int> STRINTMAP;
typedef map<string,int>::iterator STRINTMAP_ITER;

typedef map<int,string> INTSTRMAP;
typedef map<int,string>::iterator INTSTRMAP_ITER;

typedef map<int,double> INTDBLMAP;
typedef map<int,double>::iterator INTDBLMAP_ITER;

typedef map<string,double> STRDBLMAP;
typedef map<string,double>::iterator STRDBLMAP_ITER;

typedef map<int,double> INTDBLMAP;
typedef map<int,double>::iterator INTDBLMAP_ITER;

typedef map<int,int> INTINTMAP;
typedef map<int,int>::iterator INTINTMAP_ITER;
#define CONSTR_LEN 256
